name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [20.9.0, 22]
        include:
          - os: windows-latest
            node_version: 20.9.0
          - os: macos-latest
            node_version: 20.9.0
      fail-fast: false

    name: 'Test: node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the packages
        run: pnpm build

      - name: Test (Linux)
        if: runner.os == 'Linux'
        run: |
          pnpm run test:skip-vs
          cd packages/vscode
          xvfb-run -a pnpm test
          cd ../ts-plugin
          xvfb-run -a pnpm test

      - name: Test
        run: pnpm test
        if: runner.os != 'Linux'
